// apps/react/pages/_app.js
import '../styles.css';
import Link from 'next/link';

export default function App({ Component, pageProps }) {
  return (
    <>
      <header className="site-header">
        <nav className="nav">
          <Link className="brand" href="/">SS JS QA</Link>
          <div className="links">
            <Link href="/financial-aid">Financial Aid</Link>
            <Link href="/graduate-programs">Graduate Programs</Link>
            <Link href="/undergraduate-programs">Undergraduate Programs</Link>
            <Link href="/contact">Contact</Link>
            <Link href="/search">Search</Link>
          </div>
        </nav>
      </header>
      <main className="container">
        <Component {...pageProps} />
      </main>
      <footer className="site-footer">
        <small>Demo app for testing SearchStax UI kit integration.</small>
      </footer>
    </>
  );
}

// apps/vue/src/App.vue
<template>
  <header class="site-header">
    <nav class="nav">
      <router-link class="brand" to="/">SS JS QA</router-link>
      <div class="links">
        <router-link to="/financial-aid">Financial Aid</router-link>
        <router-link to="/graduate-programs">Graduate Programs</router-link>
        <router-link to="/undergraduate-programs">Undergraduate Programs</router-link>
        <router-link to="/contact">Contact</router-link>
        <router-link to="/search">Search</router-link>
      </div>
    </nav>
  </header>
  <main class="container">
    <RouterView />
  </main>
  <footer class="site-footer">
    <small>Demo app for testing SearchStax UI kit integration.</small>
  </footer>
</template>
