// apps/react/pages/contact.js
import Head from 'next/head';

export default function Contact() {
  return (
    <>
      <Head>
        <title>SS JS QA — React | Contact</title>
      </Head>
      <h1>Contact</h1>
      <p>Reach out to departments or support.</p>
      <div id="searchstax-placeholder-contact" style={{ padding: 16, border: '2px dashed #999', borderRadius: 8 }}>
        Search UI kit mounts here later.
      </div>
    </>
  );
}

// apps/angular/src/app/pages/contact.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-contact',
  standalone: true,
  template: `
    <h1>Contact</h1>
    <p class="lead">Reach out to departments or support.</p>
    <section class="section">
      <h2>Search Placeholder</h2>
      <div class="placeholder" id="searchstax-placeholder-contact">
        Search UI kit mounts here later.
      </div>
    </section>
  `,
})
export class ContactComponent {}
